version: '3.1'
services:
  eqc-for-nco-service:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: eqc-for-nco:latest
    container_name: eqc-for-nco-container
    volumes:
      - ./:/home
    network_mode: bridge
    command: "tail -f /dev/null"
  