version: '3.1'
services:
  eqc-for-nco-service:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: eqc-for-nco:latest
    container_name: eqc-for-nco-container
    ports:
      - 8888:8888
      - 8000:8000
      - 83:83
      - 80:80
      - 50:50
      - 443:443
    volumes:
      - ./:/home
    network_mode: bridge
    command: "tail -f /dev/null"
  